version: '3.8'

services:
  teacher-session-service:
    build:
      context: ./backend/teacher-session-service
      dockerfile: ../../config/backend/teacher-session-service/Dockerfile
    container_name: tsp_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend/teacher-session-service:/app_src
